// Payment Collection & Receipt Management Service for LOT Field Collection Platform

import { supabase } from "../config/supabase.config.js";
import { Database, PaymentMode } from "../types/database.types.js";

type PaymentRow = Database['public']['Tables']['case_payments']['Row'];

export class PaymentService {
  /**
   * Upload Receipt Photo to Supabase Storage ('receipt-photo' bucket)
   */
  static async uploadReceiptPhoto(receiptNumber: string, fileBlob: Blob, fileExtension = "jpg"): Promise<string> {
    const filePath = `receipt_${receiptNumber}_${Date.now()}.${fileExtension}`;
    
    const { error: uploadErr } = await supabase.storage
      .from("receipt-photo")
      .upload(filePath, fileBlob, { upsert: true });

    if (uploadErr) throw uploadErr;

    const { data } = supabase.storage.from("receipt-photo").getPublicUrl(filePath);
    return data.publicUrl;
  }

  /**
   * Process and record a field payment collection
   */
  static async processPayment(params: {
    caseId: string;
    loanNo: string;
    customerName: string;
    executiveId: string;
    executiveName: string;
    branchName: string;
    amountPaid: number;
    paymentMode: PaymentMode;
    paymentReference?: string;
    notes?: string;
  }): Promise<{ payment: PaymentRow; receiptNumber: string }> {
    if (!params.amountPaid || params.amountPaid <= 0) {
      throw new Error("Payment collection amount must be strictly greater than 0.");
    }

    // Insert directly into case_payments table (receipt number is auto-generated by database)
    const { data: dbPay, error: dbErr } = await supabase
      .from("case_payments")
      .insert({
        case_id: params.caseId,
        loan_no: params.loanNo,
        customer_name: params.customerName,
        executive_id: params.executiveId,
        executive_name: params.executiveName,
        branch_name: params.branchName,
        amount_paid: params.amountPaid,
        payment_mode: params.paymentMode,
        payment_reference: params.paymentReference || null,
        notes: params.notes || null,
      })
      .select("*")
      .single();

    if (dbErr) throw dbErr;

    return { payment: dbPay as PaymentRow, receiptNumber: dbPay.receipt_number };
  }

  /**
   * Get Receipt Details for Printing or Verification
   */
  static async getReceipt(receiptNumber: string): Promise<any> {
    const { data, error } = await supabase
      .from("case_payments")
      .select("*, cases(*)")
      .eq("receipt_number", receiptNumber)
      .single();

    if (error) throw error;
    return data;
  }

  /**
   * Get Payment History for a Case
   */
  static async getCasePayments(caseId: string): Promise<PaymentRow[]> {
    const { data, error } = await supabase
      .from("case_payments")
      .select("*")
      .eq("case_id", caseId)
      .order("created_at", { ascending: false });

    if (error) throw error;
    return data || [];
  }

  /**
   * Get All Payments for Collection Trend Analysis
   */
  static async getAllPayments(): Promise<Pick<PaymentRow, 'amount_paid' | 'created_at'>[]> {
    const { data, error } = await supabase
      .from("case_payments")
      .select("amount_paid, created_at")
      .order("created_at", { ascending: true });

    if (error) throw error;
    return data || [];
  }
}
